# Generated by Django 2.0.13 on 2019-07-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0017_imageset_zip_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABMLExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recommender', models.IntegerField(choices=[(0, 'baseline'), (1, 'abml')], default=0)),
                ('image_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.ImageSet')),
            ],
        ),
    ]
