# Generated by Django 2.0.13 on 2019-07-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_points'),
        ('abml', '0002_auto_20190717_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='abmlexperiment',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Team'),
        ),
    ]
